export const marks = [
  { value: "buick", label: "Buick" },
  { value: "volvo", label: "Volvo" },
  { value: "hummer", label: "HUMMER" },
  { value: "subaru", label: "Subaru" },
  { value: "mitsubishi", label: "Mitsubishi" },
  { value: "nissan", label: "Nissan" },
  { value: "lincoln", label: "Lincoln" },
  { value: "gmc", label: "GMC" },
  { value: "hyundai", label: "Hyundai" },
  { value: "mini", label: "MINI" },
  { value: "bentley", label: "Bentley" },
  { value: "aston martin", label: "Aston Martin" },
  { value: "pontiac", label: "Pontiac" },
  { value: "land rover", label: "Land Rover" },
  { value: "lamborghini", label: "Lamborghini" },
  { value: "mazda", label: "Mazda" },
  { value: "bmw", label: "BMW" },
  { value: "mercedes-benz", label: "Mercedes-Benz" },
  { value: "chrysler", label: "Chrysler" },
  { value: "kia", label: "Kia" },
  { value: "opel", label: "Opel" },
  { value: "fiat", label: "Fiat" },
];
